services:
  ds4:
    # controller
    image: brean/ds4-ros2:humble
    build:
      context: ./ds4/
      dockerfile: ./Dockerfile
    privileged: True
    volumes:
      - /dev:/dev

  cmd_vel:
    # output of cmd_vel
    build:
      context: ./cmd_vel/
      dockerfile: ./Dockerfile
